
services:
  app:
    container_name: rick-and-morty-dev
    image: rick-and-morty-dev
    build:
      target: development_build
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000